"""
Modal dialog used by Today + Insights to (re-)build a study plan.

Captures target score, weeks-until-test, and hours-per-week. The plan
itself is generated by `services.study_plan.generate_plan` after the user
clicks OK; the dialog is just the form.
"""
import wx


class StudyPlanDialog(wx.Dialog):
    """Capture target / weeks / hours; the caller turns these into a plan."""

    def __init__(self, parent):
        super().__init__(parent, title="Create Study Plan", size=(400, 280))
        sizer = wx.BoxSizer(wx.VERTICAL)

        sizer.Add(wx.StaticText(self, label="Target combined score (260-340):"),
                  0, wx.ALL, 8)
        self.target = wx.SpinCtrl(self, min=260, max=340, initial=320)
        sizer.Add(self.target, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 8)

        sizer.Add(wx.StaticText(self, label="Weeks until test:"), 0, wx.ALL, 8)
        self.weeks = wx.SpinCtrl(self, min=1, max=52, initial=8)
        sizer.Add(self.weeks, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 8)

        sizer.Add(wx.StaticText(self, label="Hours per week:"), 0, wx.ALL, 8)
        self.hours = wx.SpinCtrl(self, min=1, max=80, initial=10)
        sizer.Add(self.hours, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 8)

        btn_sizer = self.CreateStdDialogButtonSizer(wx.OK | wx.CANCEL)
        sizer.Add(btn_sizer, 0, wx.ALL | wx.ALIGN_RIGHT, 12)

        self.SetSizer(sizer)

    def get_params(self):
        return {
            "target_score": self.target.GetValue(),
            "weeks": self.weeks.GetValue(),
            "hours_per_week": self.hours.GetValue(),
        }
