"""
One-shot script: retire the 73 questions the audit flagged as corrupted.

Marks `status='retired'` on each so that:
  - `services.question_bank.select_questions_composed` and
    `select_drill_smart` skip them (both filter on `status='live'`)
  - the diagnostic + practice flows never serve them
  - the user-visible "wrong answer + mismatched explanation" reports stop

Idempotent: re-running on already-retired rows is a no-op. The same QID
list lives inside migration `006_retire_corrupted_2026_04` so cloned-fresh
machines reach the same state without running this script.

PR 7's `regenerate_retired_answers.py` later attempts to re-derive the
correct answer + explanation via a two-pass LLM consensus and un-retires
on agreement.

Usage:
    venv/bin/python scripts/retire_corrupted_questions.py        # apply
    venv/bin/python scripts/retire_corrupted_questions.py --dry-run
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models.database import db, Question, init_db
from services.log import get_logger

logger = get_logger("retire_corrupted")


# Generated by audit_data_corruption.py on 2026-04-18.
# 61 verbal answer-key mismatches + 5 quant + 11 LLM "Wait—let me
# reconsider" artifacts (with overlap) = 73 unique IDs. The migration
# `006_retire_corrupted_2026_04` carries the same list so re-clones get
# the same DB state without running this script.
CORRUPT_QIDS = [
    8, 169, 264, 432, 433, 434, 441, 442, 443, 461, 462, 469,
    627, 633, 691, 722, 751, 864, 871, 908, 1029, 1152, 1177, 1191,
    1206, 1269, 1270, 1278, 1279, 1280, 1282, 1285, 1288, 1291, 1292, 1293,
    1295, 1300, 1301, 1305, 1306, 1310, 1314, 1316, 1319, 1321, 1324, 1326,
    1327, 1328, 1330, 1334, 1337, 1348, 1350, 1355, 1356, 1357, 1361, 1364,
    1370, 1371, 1372, 1373, 1374, 1375, 1377, 1379, 1380, 1381, 2253, 2255,
    2418,
]

# Second batch found 2026-04-18 by structural audit (user-reported
# screenshots): 1 TC with mismatched answer key (qid 604, "Loki" — same
# bug class as the first batch but missed by the first-pass heuristic
# because the explanation didn't use the giveaway "correct answer is X"
# phrase) + 111 QC questions whose prompts lack the "Quantity A:" /
# "Quantity B:" labels (the Quantity values were concatenated into the
# stem during extraction, leaving the rendered question structurally
# unanswerable) + 1 quant DI question whose chart wasn't extracted.
# The migration `007_retire_incomplete_2026_04` carries the same list.
INCOMPLETE_QIDS = [
    604, 678, 679, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690,
    692, 693, 694, 695, 696, 698, 699, 700, 701, 702, 703, 704, 705,
    706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 719,
    720, 721, 723, 724, 725, 726, 727, 729, 730, 731, 732, 733, 734,
    735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747,
    748, 749, 750, 752, 753, 754, 755, 756, 757, 758, 760, 761, 762,
    764, 765, 766, 767, 768, 770, 771, 772, 773, 774, 775, 776, 777,
    778, 779, 780, 781, 782, 783, 785, 786, 787, 788, 789, 790, 792,
    793, 794, 795, 797, 798, 799, 800, 948, 2214,
]

# Third batch (2026-04-18): 22 RC questions whose option E text leaked
# past its boundary and absorbed the "Questions N-M refer to the
# following passage. <passage…>" marker that belonged to the *next*
# question set. The leaked option is unreadable and the next question
# set was extracted without its passage. Carried by migration
# `008_retire_option_leak_2026_04`.
OPTION_LEAK_QIDS = [
    810, 812, 813, 816, 817, 820, 824, 825, 829, 831, 837, 838, 840,
    1022, 1025, 1029, 1034, 1037, 1039, 1043, 1050, 1056,
]

ALL_RETIRE_QIDS = sorted(set(CORRUPT_QIDS + INCOMPLETE_QIDS + OPTION_LEAK_QIDS))


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dry-run", action="store_true",
                   help="Print what would change; do not write")
    args = p.parse_args()

    init_db()
    db.connect(reuse_if_open=True)

    rows = list(Question.select().where(Question.id.in_(ALL_RETIRE_QIDS)))
    not_found = set(ALL_RETIRE_QIDS) - {r.id for r in rows}
    already_retired = [r for r in rows if r.status == "retired"]
    to_retire = [r for r in rows if r.status != "retired"]

    print(f"Plan:")
    print(f"  total in retire list:       {len(ALL_RETIRE_QIDS)}")
    print(f"  found in DB:                {len(rows)}")
    print(f"  not found (skipped):        {len(not_found)}")
    print(f"  already retired (no-op):    {len(already_retired)}")
    print(f"  will be marked retired:     {len(to_retire)}")
    if not_found:
        print(f"  missing IDs: {sorted(not_found)}")

    if args.dry_run:
        print()
        print("Dry-run; no changes written. Re-run without --dry-run to apply.")
        return

    if not to_retire:
        print()
        print("Nothing to do; every flagged question is already retired.")
        return

    print()
    print(f"Writing status='retired' to {len(to_retire)} rows...")
    with db.atomic():
        n = (Question
             .update(status="retired")
             .where(Question.id.in_([r.id for r in to_retire]))
             .execute())
    logger.info("retired %d corrupted questions", n)
    print(f"Done. Retired {n} questions.")


if __name__ == "__main__":
    main()
