"""
One-shot script: retire the 73 questions the audit flagged as corrupted.

Marks `status='retired'` on each so that:
  - `services.question_bank.select_questions_composed` and
    `select_drill_smart` skip them (both filter on `status='live'`)
  - the diagnostic + practice flows never serve them
  - the user-visible "wrong answer + mismatched explanation" reports stop

Idempotent: re-running on already-retired rows is a no-op. The same QID
list lives inside migration `006_retire_corrupted_2026_04` so cloned-fresh
machines reach the same state without running this script.

PR 7's `regenerate_retired_answers.py` later attempts to re-derive the
correct answer + explanation via a two-pass LLM consensus and un-retires
on agreement.

Usage:
    venv/bin/python scripts/retire_corrupted_questions.py        # apply
    venv/bin/python scripts/retire_corrupted_questions.py --dry-run
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models.database import db, Question, init_db
from services.log import get_logger

logger = get_logger("retire_corrupted")


# Generated by audit_data_corruption.py on 2026-04-18.
# 61 verbal answer-key mismatches + 5 quant + 11 LLM "Wait—let me
# reconsider" artifacts (with overlap) = 73 unique IDs. The migration
# `006_retire_corrupted_2026_04` carries the same list so re-clones get
# the same DB state without running this script.
CORRUPT_QIDS = [
    8, 169, 264, 432, 433, 434, 441, 442, 443, 461, 462, 469,
    627, 633, 691, 722, 751, 864, 871, 908, 1029, 1152, 1177, 1191,
    1206, 1269, 1270, 1278, 1279, 1280, 1282, 1285, 1288, 1291, 1292, 1293,
    1295, 1300, 1301, 1305, 1306, 1310, 1314, 1316, 1319, 1321, 1324, 1326,
    1327, 1328, 1330, 1334, 1337, 1348, 1350, 1355, 1356, 1357, 1361, 1364,
    1370, 1371, 1372, 1373, 1374, 1375, 1377, 1379, 1380, 1381, 2253, 2255,
    2418,
]


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dry-run", action="store_true",
                   help="Print what would change; do not write")
    args = p.parse_args()

    init_db()
    db.connect(reuse_if_open=True)

    rows = list(Question.select().where(Question.id.in_(CORRUPT_QIDS)))
    not_found = set(CORRUPT_QIDS) - {r.id for r in rows}
    already_retired = [r for r in rows if r.status == "retired"]
    to_retire = [r for r in rows if r.status != "retired"]

    print(f"Plan:")
    print(f"  total in retire list:       {len(CORRUPT_QIDS)}")
    print(f"  found in DB:                {len(rows)}")
    print(f"  not found (skipped):        {len(not_found)}")
    print(f"  already retired (no-op):    {len(already_retired)}")
    print(f"  will be marked retired:     {len(to_retire)}")
    if not_found:
        print(f"  missing IDs: {sorted(not_found)}")

    if args.dry_run:
        print()
        print("Dry-run; no changes written. Re-run without --dry-run to apply.")
        return

    if not to_retire:
        print()
        print("Nothing to do; every flagged question is already retired.")
        return

    print()
    print(f"Writing status='retired' to {len(to_retire)} rows...")
    with db.atomic():
        n = (Question
             .update(status="retired")
             .where(Question.id.in_([r.id for r in to_retire]))
             .execute())
    logger.info("retired %d corrupted questions", n)
    print(f"Done. Retired {n} questions.")


if __name__ == "__main__":
    main()
